### ISSUE TITLE
assorted CMS content bugs

### ISSUE THREAD

**Issue by davelandry** [datamexico/datamexico-site#39]

**Comment by alexandersimoes** [comment]
- [ ] balanza comercial line chart not working (https://dev.datamexico.org/es/profile/geo/1#trade-balance)
- [ ] municipality maps not working (Balanza Comercial por Municipio)
- [ ] IED section need title separator 
- [ ] IED categories are missing titles in tree maps
- [ ] IED need to filter out negative values (otherwise treemaps look weird)
<img width="573" alt="Screen Shot 2019-12-02 at 12 38 27 PM" src="https://user-images.githubusercontent.com/252276/69993637-38882180-151a-11ea-8e0e-3ca920fbb40c.png">
- [ ] need to clarify $ type in all tooltips (USD or MEX)

**Comment by alexandersimoes** [comment]
Another thing is that the geo pages are very slow to load... for this reason it may make sense to remove the timeline for many of the charts and only show data for the latest year available.
