### ISSUE TITLE
text language problem in RCA calculation

### ISSUE THREAD

**Issue by ffigueroal** [datamexico/datamexico-site#42]
When the RCA is calculated, it returns the english categories name by default, regardless of the specified locale.

Example:
![image](https://user-images.githubusercontent.com/39899484/70078147-eeb63e80-15e0-11ea-8a26-e2d90928c02c.png)

**Comment by cnavarreteliz** [comment]
related with tesseract-olap/tesseract/issues/229

**Comment by MarcioPorto** [comment]
Updating the description of this ticket, since it works in the logic layer: https://api.oec.world/tesseract/data.jsonrecords?cube=trade_i_baci_a_92&drilldowns=Exporter+Country&locale=es&measures=Trade+Value&parents=false&rca=Year%2CHS2%2CTrade+Value&sparse=false&Exporter+Country=sabra.

Turns out that raw Tesseract does not currently have support for a `locale` param.
